spring:
  application:
    name: smart-portfolio-builder
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: luutrieuvi2003@gmail.com
    password: bacrofozncoqsiqg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: @spring.profiles.active@
